import type { ScanReport } from "../domain/models";

export const mockReport: ScanReport = {
  driveSummary: {
    drive: "C:",
    totalBytes: 251535081472,
    freeBytes: 27938717696,
  },
  partial: false,
  scanStartedAt: "2026-06-11T00:00:00Z",
  scanFinishedAt: "2026-06-11T00:00:05Z",
  items: [
    {
      id: "user-temp",
      title: "用户临时文件",
      description: "软件运行时留下的临时材料，通常可以安全删除。",
      sourceCategory: "system",
      riskLevel: "recommended",
      cleanupAction: "directDelete",
      estimatedBytes: 386924544,
      defaultSelected: true,
      userVisiblePathHint: "当前用户临时目录",
      reasons: ["命中安全白名单。"],
      warnings: [],
    },
    {
      id: "wechat-video-cache",
      title: "微信视频缓存子目录",
      description: "精确命中的微信视频缓存子目录，可能包含你仍想保留的视频。",
      sourceCategory: "wechat",
      riskLevel: "highRisk",
      cleanupAction: "directDelete",
      estimatedBytes: 980000000,
      defaultSelected: false,
      userVisiblePathHint: "微信视频缓存子目录",
      reasons: ["命中精确子目录规则，但仍属于用户数据。"],
      warnings: ["可能删除聊天中的视频缓存，删除后无法保证恢复。"],
    },
    {
      id: "wechat-data-root",
      title: "微信数据根目录",
      description: "微信完整数据目录包含聊天记录、图片、视频、文件和数据库。",
      sourceCategory: "wechat",
      riskLevel: "notCleanable",
      cleanupAction: "explainOnly",
      estimatedBytes: 4620000000,
      defaultSelected: false,
      userVisiblePathHint: "微信用户数据根目录",
      reasons: ["V0.1 不提供聊天软件根目录删除。"],
      warnings: ["请在微信内置设置中管理聊天文件，或等待后续版本提供更细粒度分类。"],
    },
    {
      id: "tool-config-ref",
      title: "工具旧版本运行目录",
      description: "这个目录看起来像旧版本，但某个工具仍从这里启动。",
      sourceCategory: "installersOldVersions",
      riskLevel: "notCleanable",
      cleanupAction: "blockedByConfigReference",
      estimatedBytes: 640000000,
      defaultSelected: false,
      userVisiblePathHint: "工具扩展目录",
      reasons: ["被工具配置引用。"],
      warnings: ["清理可能导致工具启动失败，已自动跳过。"],
    },
  ],
};
